---
experimentTitle: Example Rescoring
searchResults: example/data/msms.txt
searchEngine: maxquant
outputFolder: example/output
scansFolder: example/data
scansFormat: mgf
collisionEnergy: 33
rescoreMethod: mokapot
mzAccuracy: 0.02
